version: 1

disable_existing_loggers: False

formatters:
    simple:
        format: "%(asctime)s [%(name)s] [%(levelname)s] :%(levelno)s: %(message)s"
        datefmt: '%Y-%m-%d %H:%M:%S'
    detail_stdout:
        class: colorlog.ColoredFormatter
        format: '%(levelname)-7s %(asctime)s %(filename)10s:%(lineno)3d] %(log_color)s%(message)s'
        datefmt: '%H:%M:%S'
    detail_file:
        format: '%(levelname)-7s %(asctime)s %(filename)s:%(lineno)3d] %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: detail_stdout
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: detail_file
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: detail_file
        filename: errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8
root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
